services:
  cloud-torrent:
    image: ghcr.io/hekrun/cloud-torrent-downloader:latest
    pull_policy: always
    container_name: cloud-torrent
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DOWNLOAD_DIR: /data/downloads
      STATE_DIR: /data/state
    volumes:
      - cloud-torrent-data:/data

volumes:
  cloud-torrent-data:
